### ISSUE TITLE
Package failed in win10 16299

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/msix-docs#141]
@kenlost commented 23 hours ago

I use VS 2017 create a UWP project whose TargetPlatformMinVersion is set as 10.0.16299.0.
Then I create app package. the .appxupload package will crash at startup with exception:
0x00007FFF91669709 (KernelBase.dll) (codecs.exe 中)处有未经处理的异常: 0xE0434352 (参数: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFF73D00000)。
0x00007FFF73D00000 is the address of clr.dll

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [Packaging MSIX apps - MSIX](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by Huios** [comment]
Hi @kenlost 
When generating a package can you try selecting the "Sideloading" option instead so that you'll get a .msix or .appx and see if installing that works?

If not, can you please file an item on Feedback Hub under [Developer Platform > App Deployment] with the package and details of your OS version. Please post a link to the feedback item on here when you're done.

Thank you!
Tanaka (MSFT)
