### ISSUE TITLE
Command line utility should actually be MsixPackagingToolCLI.exe -- NOT MsixPackagingTool.exe

### ISSUE THREAD

**Issue by Trentent** [MicrosoftDocs/msix-docs#180]
[Enter feedback here]

Command line utility should actually be MsixPackagingToolCLI.exe -- NOT MsixPackagingTool.exe

Please update the lines that mention MsixPackagingTool.exe to MsixPackagingToolCLI.exe.

In addition, MsixPackagingToolCLI.exe needs to be copied out of the WindowsApps folder to a location you have full rights to execute.  WindowsApps don't appear to allow command-line execution of individual exe's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad6dc2e-0d05-9bfb-498e-306e1dc8d572
* Version Independent ID: 323e44fe-70c8-8be8-db1e-7b9dec4bdaf7
* Content: [Create a package using the command line interface - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/package-conversion-command-line)
* Content Source: [msix-src/packaging-tool/package-conversion-command-line.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/package-conversion-command-line.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Hi @Trentent, 

Could you please provide some more information about why you believe this is wrong? Running the MsixPackagingTool.exe in an elevated Command Prompt is correct and how we expect people to use it. It doesn't require moving anything from WindowsApps either.

**Comment by Trentent** [comment]
Hello Sharla,

#1 - There is no command line options for the MSIXPackagingTool.exe.  The options are available in MSIXPackagingToolCLI.exe.  It is literally impossible to run MSIXPackagingTool.exe with any parameters like stated in the article because they do not exist in the program.

#2 - Users are not able to access the WindowsApps folder and *are explicitly denied* from launching exe's directly from there. This includes attempting to launch programs via the command-line.

Raymond Chen of Microsoft said it best:<https://devblogs.microsoft.com/oldnewthing/20200113-00/?p=103322>

the %PROGRAMFILES%\WindowsApps directory is non-enumerable to prevent users from browsing into it with Explorer and trying to double-click the programs in it. Double-clicking those programs won’t work, because they are UWP apps which execute in a special environment that needs to be set up first. Blocking enumeration prevents users from getting themselves into trouble. The programs themselves and their associated data files must still be readable, because when the program runs, it needs to be able to read those data files.

Thanks,

Trentent


________________________________

**Comment by sharlaakers** [comment]
Hi, 

You are correct, the actual executable is called MSIXPackagingToolCLI.exe - however we do have an [app execution alias](https://docs.microsoft.com/windows/apps/desktop/modernize/desktop-to-uwp-extensions#start-your-application-by-using-an-alias) for the packaging tool, which is the MSIXPackagingTool.exe. This exists so that you do not have to specify a path within your command line to launch the command line of the tool and to prevent the need to access anything in WindowsApps folder.  You can launch an elevated Command Prompt and type MSIXPackagingTool.exe then hit enter and you will see all of the options available to you with this executable. 

![image](https://user-images.githubusercontent.com/45182130/94862288-995be100-03ed-11eb-8cdd-ccd8ec4f4c0c.png)
