### ISSUE TITLE
PSF Scripts Requirements

### ISSUE THREAD

**Issue by jamesaepp** [MicrosoftDocs/msix-docs#200]
> To enable scripts to run, you need to set the PowerShell execution policy to RemoteSigned. You can do this by running this command:

Is this done on the "host machine"? Or while you're building a package? Does the setting "inside" the package need to match what's outside the package? How does a powershell script running "inside" the app choose its execution policy? This really needs to be made less vague.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6576833e-f6e5-de9e-e7b5-f0dccf047eb0
* Version Independent ID: 7068b63b-3a4b-d6ef-796a-22ae615b4245
* Content: [Run scripts with the Package Support Framework - MSIX](https://docs.microsoft.com/en-us/windows/msix/psf/run-scripts-with-package-support-framework)
* Content Source: [msix-src/psf/run-scripts-with-package-support-framework.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/psf/run-scripts-with-package-support-framework.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by dianmsft** [comment]
Thanks for providing feedback and question. The execution policy needs to be set on the computer that will be running the scripts.  This is usually the computer running the package because the package will run PowerShell to run the scripts. PSF and the script uses the execution policy set in PowerShell prior to the package execution.  PSF does not have any internal settings on the execution policy.  PSF uses the system’s powerhsell.exe to run scripts, and thus, the execution policy needs to be set prior to script execution. We will be updating the docs to provide this clarification.
