### ISSUE TITLE
Improve documentation on how to use MSIX Core to build an installer from code

### ISSUE THREAD

**Issue by szilardd** [MicrosoftDocs/msix-docs#213]
I have a .NET Framework WinForms application and I want to create an MSIX setup for it. It should work on Windows 7 and 10. Having trouble understanding the description for MSIX Core, what can it do, and how to use it. Hoping to get some help and maybe based on this create a PR to improve the documentation.

I'm referring to this section from the documentation that should allow creating an installer from source code using MSIX core 

https://docs.microsoft.com/en-us/windows/msix/msix-core/msixcore-clickonce-solution#use-the-msix-core-installer-to-build-the-clickonce-application

1. "_Find your application application ClickOnce setup.exe._"

Should I already have a `setup.exe` for my app built with ClickOnce? I'm assuming not because the purpose of MSIX Core is to build the installer. There's also a small 'typo', the `application` word appears twice.

2. "_Navigate to the directory where you downloaded the setup.exe file and then run this command:_"

I don't understand this sentence. Which `setup.exe` should I download?

3. "_Make sure you have followed the instructions to clone, build and publish the MSIX Core solution in Visual Studio._"

I can't seem to find these instructions. Can we have a link to this page?

4. `setup-exe - url=<location of your msix in the webservice>`

Is this code snippet correct? Where is the `setup-exe` executable? Should there be a space character before the `url` switch?

5. How can these steps be done in a CI environment (e.g. Azure DevOps)? How can an app be packaged in DevOps without manual steps?

Thanks

**Comment by dianmsft** [comment]
Hi there, the page is in the middle of being updated. To answer your questions: 

1. "Find your application application ClickOnce setup.exe."
Should I already have a setup.exe for my app built with ClickOnce? I'm assuming not because the purpose of MSIX Core is to build the installer. There's also a small 'typo', the application word appears twice.
The instructions are meant to guide you to the Git Project, build and publish it via Visual studio project 


2. "Navigate to the directory where you downloaded the setup.exe file and then run this command:"
I don't understand this sentence. Which setup.exe should I download?
This should not say “downloaded”. It should say “published”, referring to the setup.exe that was published via the visual studio project

3. "Make sure you have followed the instructions to clone, build and publish the MSIX Core solution in Visual Studio."
I can't seem to find these instructions. Can we have a link to this page?
This is the github project https://github.com/microsoft/msix-packaging/tree/master/MsixCore We don’t have separate instructions for the ClickONce specifically, but I think it’s part of the overall solution and can just be built.

4. setup-exe - url=<location of your msix in the webservice>
Is this code snippet correct? Where is the setup-exe executable? Should there be a space character before the url switch?
No, the formatting of the code snippet must’ve been mangled. It should be setup.exe (referring to the published setup.exe location) and no space in the -url=
Furthermore, the format of the url needs to look something like 
.\setup.exe -url="https://appinstallerdemo.azurewebsites.net/MSIXCore/msixmgrWrapper.application?https://appinstallerdemo.azurewebsites.net/MSIXCore/notepadplus.msix#"


5. How can these steps be done in a CI environment (e.g. Azure DevOps)? How can an app be packaged in DevOps without manual steps?
The project can be built/published in DevOps. The manual steps can all be done in a scripted task in DevOps.
