### ISSUE TITLE
Unable to get VM's 

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/msix-docs#236]
When trying to scan for MSIX VM on Hyper-V you receive error 0x80131500. The documentation states you need to stop event collectors but the reason in my case is I had the VMware PowerShell module installed which also uses Get-VM. The Azure Get-VM command would not work in this case. Uninstalling VMware PowerCLI module fixed this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af06d0aa-a867-f314-640d-49b462850299
* Version Independent ID: 1ab6ed42-0509-153c-ec6a-8bce23833c3b
* Content: [MSIX Packaging Tool Known Issues and Troubleshooting Tips - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/tool-known-issues)
* Content Source: [msix-src/packaging-tool/tool-known-issues.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/tool-known-issues.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by dianmsft** [comment]
Thanks for submitting your question. In this scenario, you have a module loaded that exported a `Get-VM` cmdlet.  Since that module is already loaded, then `Get-VM` will refer to that module instead of Azure.  This is by-design.  This blog post explains other solutions than unloading the VMWare module: https://devblogs.microsoft.com/scripting/powershell-naming-conflicts/

**Comment by MarcLaf** [comment]
Yes I understand that's what's happening so it would possibly make sense for the MSIX program to reference the real Get-VM command by the absolute path (Hyper-V\Get-VM) instead of just Get-VM in the chance that the user has other modules loaded, just like I experienced.
