### ISSUE TITLE
Package acceptance validation error: The package xyz.msix doesn't contain any Application elements in the app manifest file.

### ISSUE THREAD

**Issue by bksubhuti** [MicrosoftDocs/msix-docs#237]
No way to resolve this.
Package acceptance validation error: The package 26554BhikkhuSangha.TipitakaPaliProjector_1.0.9.0_x64__653amgjsk4fne.msix doesn't contain any Application elements in the app manifest file.

How to fix this.. I need to update quickly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45e4355-afe9-ad10-0772-032b2ff288bd
* Version Independent ID: 3d281169-5030-2859-4c83-9cfc9fc3f653
* Content: [Create an MSIX package from any desktop installer - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-app-package)
* Content Source: [msix-src/packaging-tool/create-app-package.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/create-app-package.md)
* Product: **msix**
* GitHub Login: @sharlaakers
* Microsoft Alias: **shakers**

**Comment by sharlaakers** [comment]
Hi, 

Unfortunately without more information we can't know what the issue is. Could you please file a [Feedback Hub](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/tool-known-issues#sending-feedback) item or post on our [Tech Community](https://techcommunity.microsoft.com/t5/msix/ct-p/MSIX) with more information so that we can help you troubleshoot?

Best,
Sharla
