### ISSUE TITLE
The update is applied immediately after AddPackageAsync.

### ISSUE THREAD

**Issue by HppZ** [MicrosoftDocs/msix-docs#301]
from doc: 
>The update will be applied the next time your app is shut down.

`await packagemanager.AddPackageAsync(new Uri("https://trial3.azurewebsites.net/HRApp/HRApp.msix"), null, AddPackageOptions.ForceApplicationShutdown`

same for `UpdatePackageAsync`.

but according to my test, the update is applied immediately after AddPackageAsync, and the app is killed by Windows.
why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dbc475-482a-3e2f-b41e-bb9d35d100e5
* Version Independent ID: 93e1b53d-8150-5693-ca85-acb317f1f666
* Content: [Update non-Store published apps from your code - MSIX](https://docs.microsoft.com/en-us/windows/msix/non-store-developer-updates)
* Content Source: [msix-src/non-store-developer-updates.md](https://github.com/microsoftdocs/msix-docs/blob/main/msix-src/non-store-developer-updates.md)
* Product: **msix**
* GitHub Login: @Huios
* Microsoft Alias: **diahar**

**Comment by HarshadaKshirsagar** [comment]
The right **AddPackageOptions**' property to be used here would be **DeferRegistrationWhenPackagesAreInUse**. It is a Boolean value, TRUE indicates that registration of the main package or dependency packages will be delayed until the next time the application is activated if the packages are currently in use; otherwise, FALSE. 
We will update the doc to reflect this. 

**### References:** 
**AddPackageOptions Class**
https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.addpackageoptions?view=winrt-22000

**AddPackageOptions.DeferRegistrationWhenPackagesAreInUse Property**
https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.addpackageoptions.deferregistrationwhenpackagesareinuse?view=winrt-22000#windows-management-deployment-addpackageoptions-deferregistrationwhenpackagesareinuse

**Comment by HppZ** [comment]
and what is the difference between `AddPackage*` and `UpdatePackage*`？

**Comment by HarshadaKshirsagar** [comment]
Both allow you to provide similar parameters. But they are intended for specific purposes. 
**AddPackageAsync** method will Adds the main package and its dependency packages for the current user, using the specified deployment options. 
**UpdatePackageAsync** Updates an installed Package or its dependency packages for the current user. An installed package can be updated only if the version of the update package is higher than that of the installed package. **If no previous version of the package exists, the operation fails.**
Hope this helps.

**Comment by HppZ** [comment]
thanks
