### ISSUE TITLE
How do I add version information from outside sources?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/msix-docs#34]
My main application uses a [nuget package](https://gitversion.readthedocs.io/en/latest/usage/msbuild-task/#msbuild-task) to derive a version for the executable.  If I wanted the same functionality in my `*.wapproj` projects, what's my best course of action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bead27ac-8ed3-9886-26e2-47f49ea1efc0
* Version Independent ID: f354c6b6-b2e0-e070-dd0d-c3452a5635fb
* Content: [Package a desktop app from source code using Visual Studio - MSIX](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net#feedback)
* Content Source: [msix-src/desktop/desktop-to-uwp-packaging-dot-net.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/desktop/desktop-to-uwp-packaging-dot-net.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by diverdan92** [comment]
@atrauzzi - since this feedback is related to the Visual Studio tooling, do you mind submitting this as a suggestion on the [Visual Studio developer community site](https://developercommunity.visualstudio.com/spaces/8/index.html)? 

You can *probably* achieve this today by using the [XmlPoke MSBuild task](https://docs.microsoft.com/en-us/visualstudio/msbuild/xmlpoke-task?view=vs-2019) but if this feedback resonates with other developers (demonstrated by activity on the Developer Community suggestion), we would likely make this easier within the Windows Application Packaging Project tooling.
